package com.sparta.springtrello.domain.activity.entity;

public enum ActivityType {
    CARD_CREATED,
    CARD_MOVED,
    CARD_ARCHIVED,
    CARD_RESTORED,
    COMMENT_ADDED,
    COMMENT_EDITED,
    COMMENT_DELETED,
    CHECKLIST_ADDED,
    CHECKLIST_ITEM_ADDED,
    CHECKLIST_ITEM_COMPLETED,
    CHECKLIST_ITEM_UNCOMPLETED,
    CHECKLIST_ITEM_DELETED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    DUE_DATE_CHANGED,
    LABEL_ADDED,
    LABEL_REMOVED

}
